#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a realtime Gemini Live pipeline.

Generated by Pipecat CLI

Required AI services:
- Google Gemini Live (Speech-to-Speech)

Run the bot using::

    uv run apsagent.py
"""


import asyncio
import json
import urllib.error
import urllib.request

from loguru import logger
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.transports.base_transport import TransportParams
import os
import re
from pathlib import Path
from typing import Any
from dotenv import load_dotenv
from google.genai.types import HttpOptions
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.transports.base_transport import BaseTransport
from pipecat.runner.types import RunnerArguments
from pipecat.services.google.gemini_live.llm import GeminiLiveLLMService, GeminiModalities
from pipecat.services.llm_service import FunctionCallParams
from pipecat.runner.types import DailyRunnerArguments
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.frames.frames import EndFrame, LLMRunFrame
from pipecat.frames.frames import Frame, TextFrame
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.transports.websocket.fastapi import FastAPIWebsocketParams, FastAPIWebsocketTransport

from rag_sharekit.rag import TieredRAG
from convtasnet_processor import ConvTasNetProcessor
from smartflo_sharekit.smartflo.smartflo_serializer import SmartFloFrameSerializer

load_dotenv(override=True)


RAG_TOOL_DECLARATION = {
    "name": "retrieve_knowledge",
    "description": (
        "Search the agriculture knowledge base for factual, product, and company-specific information. "
        "Use this for crop issues, pest or disease control, usage guidance, price or availability questions, "
        "and any Agri Phero Solutions details."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "User question to search in the knowledge base.",
            }
        },
        "required": ["query"],
    },
}


TRANSFER_MARKER = "[TRANSFER_TO_AGENT]"
ESCALATION_NUMBER = os.getenv("ESCALATION_NUMBER", "919154708539")
SMARTFLO_API_BASE_URL = os.getenv(
    "SMARTFLO_API_BASE_URL", "https://api-smartflo.tatateleservices.com"
).rstrip("/")
SMARTFLO_API_TOKEN = os.getenv("SMARTFLO_API_TOKEN", "").strip()


_INTERCOM_RE = re.compile(r"^\d{4,16}$")


def _normalize_call_direction(raw_value: str) -> str:
    value = str(raw_value or "").strip().lower()
    return value if value in {"inbound", "outbound"} else ""


def _validate_intercom(intercom_value: str) -> None:
    if not intercom_value:
        raise ValueError("missing intercom")
    if not _INTERCOM_RE.fullmatch(intercom_value):
        raise ValueError(
            "invalid intercom format (expected digits only; examples: 9196XXXXXXXX, 06XX2, 70XX2)"
        )


def _validate_call_id(call_id: str) -> None:
    if not call_id:
        raise ValueError("missing call_id")
    if str(call_id).strip().upper().startswith("MZ"):
        raise ValueError("call_id looks like streamSid (starts with MZ); expected callSid")


def _sanitize_intercom(raw_value: str) -> str:
    value = str(raw_value or "").strip()
    if value.startswith("+"):
        value = value[1:]
    value = re.sub(r"\s+", "", value)
    return value


def _post_smartflo_call_options(payload: dict) -> dict:
    url = f"{SMARTFLO_API_BASE_URL}/v1/call/options"
    data = json.dumps(payload).encode("utf-8")
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
    }
    if SMARTFLO_API_TOKEN:
        headers["Authorization"] = SMARTFLO_API_TOKEN

    request = urllib.request.Request(url, data=data, headers=headers, method="POST")
    with urllib.request.urlopen(request, timeout=6) as response:
        raw = response.read().decode("utf-8", errors="ignore")
        return json.loads(raw) if raw else {}


async def _transfer_smartflo_call(call_id: str, intercom: str, *, call_direction: str = "") -> bool:
    call_direction_norm = _normalize_call_direction(call_direction)
    if call_direction_norm and call_direction_norm != "inbound":
        logger.warning(
            "SmartFlo transfer skipped: unsupported call direction='{}' (inbound only)",
            call_direction_norm,
        )
        return False

    call_id_value = str(call_id or "").strip()
    try:
        _validate_call_id(call_id_value)
    except ValueError as exc:
        logger.error("SmartFlo transfer skipped: {}", exc)
        return False

    intercom_value = _sanitize_intercom(intercom)
    try:
        _validate_intercom(intercom_value)
    except ValueError as exc:
        logger.error("SmartFlo transfer skipped: {}", exc)
        return False

    if not SMARTFLO_API_TOKEN:
        logger.warning("SMARTFLO_API_TOKEN is not set; transfer may fail")

    payload = {
        "type": 4,
        "call_id": call_id_value,
        "intercom": intercom_value,
    }

    logger.info(
        "SmartFlo transfer request: call_id='{}' intercom='{}' direction='{}'",
        call_id_value,
        intercom_value,
        call_direction_norm or "unknown",
    )

    try:
        result = await asyncio.to_thread(_post_smartflo_call_options, payload)
        logger.info("SmartFlo transfer response: {}", result)
        return bool(result.get("success", False)) if isinstance(result, dict) else False
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="ignore") if exc.fp else ""
        logger.error("SmartFlo transfer failed: status={} body='{}'", exc.code, body)

        # Provide an actionable hint for the most common SmartFlo restriction.
        try:
            parsed = json.loads(body) if body else {}
        except Exception:
            parsed = {}
        message = str(parsed.get("message", "") if isinstance(parsed, dict) else "")
        if exc.code == 422 and "external agent" in message.lower():
            logger.warning(
                "SmartFlo rejected transfer to an external number. "
                "Fix: set ESCALATION_NUMBER to a SmartFlo Department/IVR/Extension transfer code (digits only), "
                "or ask SmartFlo support to enable external-number transfers for your account."
            )
        return False
    except Exception:
        logger.exception("SmartFlo transfer failed")
        return False


class EscalationDetector(FrameProcessor):
    """Detect transfer marker in streaming LLM text and trigger SmartFlo transfer."""

    def __init__(self, task: PipelineTask | None, call_id: str = "", call_direction: str = ""):
        super().__init__()
        self._task = task
        self._call_id = call_id
        self._call_direction = call_direction
        self._text_buffer = ""
        self._detection_phase = True
        self._is_escalation = False
        self._transfer_started = False
        self._disconnect_scheduled = False
        self._last_was_text = False

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        is_text = isinstance(frame, TextFrame) and direction == FrameDirection.DOWNSTREAM

        if not is_text:
            self._last_was_text = False
            await self.push_frame(frame, direction)
            return

        text = frame.text or ""
        if not text:
            await self.push_frame(frame, direction)
            return

        if not self._last_was_text and not self._detection_phase:
            self._detection_phase = True
            self._text_buffer = ""
            self._is_escalation = False

        self._last_was_text = True

        if not self._detection_phase:
            await self.push_frame(frame, direction)
            return

        self._text_buffer += text

        marker_index = self._text_buffer.find(TRANSFER_MARKER)
        if marker_index != -1 and not self._text_buffer[:marker_index].strip():
            self._detection_phase = False
            self._is_escalation = True

            logger.info(
                "Escalation detected; transferring call_id={} -> {}",
                self._call_id,
                _sanitize_intercom(ESCALATION_NUMBER),
            )

            if not self._transfer_started:
                self._transfer_started = True

                async def _transfer_and_maybe_end():
                    ok = await _transfer_smartflo_call(
                        self._call_id,
                        ESCALATION_NUMBER,
                        call_direction=self._call_direction,
                    )
                    if not ok:
                        logger.warning("SmartFlo transfer was not accepted; keeping call connected")
                        return

                    if self._task is None:
                        return

                    if self._disconnect_scheduled:
                        return

                    self._disconnect_scheduled = True

                    await asyncio.sleep(2)
                    logger.info("Closing SmartFlo session after successful escalation")
                    await self._task.queue_frames([EndFrame()])

                asyncio.create_task(_transfer_and_maybe_end())

            clean = self._text_buffer.replace(TRANSFER_MARKER, "").strip()
            self._text_buffer = ""
            if clean:
                frame.text = clean
                await self.push_frame(frame, direction)
            return

        if len(self._text_buffer) >= len(TRANSFER_MARKER):
            self._detection_phase = False
            frame.text = self._text_buffer
            self._text_buffer = ""
            await self.push_frame(frame, direction)
            return

        stripped = self._text_buffer.lstrip()
        if stripped and not TRANSFER_MARKER.startswith(stripped):
            self._detection_phase = False
            frame.text = self._text_buffer
            self._text_buffer = ""
            await self.push_frame(frame, direction)
            return

        return


def _strip_inline_kb(prompt_text: str) -> str:
    """Remove embedded KB blocks from prompt text so RAG is the source of truth."""
    start_token = "KNOWLEDGE BASE"
    end_token = "END OF KNOWLEDGE BASE"

    start_idx = prompt_text.find(start_token)
    if start_idx == -1:
        return prompt_text

    end_idx = prompt_text.find(end_token, start_idx)
    if end_idx == -1:
        logger.warning("System prompt includes '{}', but no '{}'. Keeping original text.", start_token, end_token)
        return prompt_text

    cleaned = prompt_text[:start_idx].strip()
    logger.info("Removed inline knowledge base section from system prompt for RAG mode")
    return cleaned


def _with_tool_guidance(system_instruction: str) -> str:
    """Append concise guidance so Gemini decides when to call RAG tools."""
    guidance = (
        "Tool usage guidance:\n"
        "- For greetings, casual chat, or purely conversational requests, answer directly without calling tools.\n"
        "- For agriculture, product, pricing, usage, pest, disease, or company factual questions, call retrieve_knowledge first.\n"
        "- For those factual questions, do not provide the final factual answer until at least one retrieve_knowledge call returns.\n"
        "- After retrieve_knowledge returns, answer only using that retrieved context for factual claims.\n"
        "- If retrieved context is empty or insufficient, clearly say the information is unavailable in the knowledge base.\n"
        "- Do not suggest representative call for every response; suggest it only for price/availability/delivery,"
        " explicit user request, or unresolved missing-information cases."
    )
    return f"{system_instruction}\n\n{guidance}".strip()


def _count_rag_chunks(context_text: str) -> int:
    """Count formatted RAG chunks in the retrieval string."""
    if not context_text.strip():
        return 0
    return context_text.count("\n\n---\n\n") + 1


def _contains_any(text: str, terms: list[str]) -> bool:
    lower = text.lower()
    return any(term.lower() in lower for term in terms)


def _is_price_delivery_intent(query: str) -> bool:
    return _contains_any(
        query,
        [
            "price",
            "availability",
            "delivery",
            "ధర",
            "లభ్యత",
            "డెలివరీ",
            "దొరుకుతాయ",
            "dispatch",
            "ఎన్ని రూపాయలు",
        ],
    )


def _is_detail_intent(query: str) -> bool:
    return _contains_any(
        query,
        [
            "వివరంగా",
            "ఇంకా",
            "మరింత",
            "పూర్తిగా",
            "in detail",
            "detailed",
            "explain",
            "full",
            "inka",
            "baga",
        ],
    )


def _limit_rag_chunks(context_text: str, max_chunks: int) -> str:
    """Keep only top-N retrieved chunks to reduce tool payload size and latency."""
    if max_chunks <= 0 or not context_text.strip():
        return context_text

    parts = [p for p in context_text.split("\n\n---\n\n") if p.strip()]
    if len(parts) <= max_chunks:
        return context_text

    return "\n\n---\n\n".join(parts[:max_chunks])


def _remove_representative_lines(context_text: str) -> str:
    """Remove repetitive transfer-to-representative suggestions from retrieved context."""
    patterns = [
        r"నేను\s*మీ\s*కాల్[^\n.]*ప్రతినిధి[^\n.]*[.।]?",
        r"ప్రతినిధితో\s*కాల్\s*కలుపుతాను[^\n.]*[.।]?",
        r"ప్రతినిధికి\s*కాల్\s*కలుప[^\n.]*[.।]?",
        r"మా\s*సంస్థ\s*ప్రతినిధి[^\n.]*[.।]?",
    ]
    cleaned = context_text
    for p in patterns:
        cleaned = re.sub(p, "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip()


def prepare_rag_context(query: str, retrieved: str, kb_text: str) -> str:
    """Apply intent-based post-processing before sending RAG context to Gemini."""
    out = retrieved

    if not _is_price_delivery_intent(query):
        out = _remove_representative_lines(out)

    return out


def _load_knowledge_text() -> str:
    """Load KB text from file path configured for RAG retrieval."""
    kb_file = os.getenv("RAG_KNOWLEDGE_BASE_FILE", "knowledge_base/apsagent_kb.txt")
    kb_path = Path(kb_file)
    if not kb_path.is_absolute():
        kb_path = Path(__file__).resolve().parent / kb_path

    kb_text = kb_path.read_text(encoding="utf-8").strip()
    if not kb_text:
        raise ValueError(f"Knowledge base file is empty: {kb_path}")

    logger.info("Loaded RAG knowledge base from '{}' ({} chars)", kb_path, len(kb_text))
    return kb_text


def create_knowledge_rag() -> tuple[object, str, str]:
    """Create RAG once at startup to keep per-turn latency low."""
    kb_text = _load_knowledge_text()
    rag_backend = os.getenv("RAG_BACKEND", "bge_m3").strip().lower()

    # BGE-M3 RAG: local embeddings, 80% accuracy, fast
    if rag_backend in {"bge_m3", "bge-m3", "rag_v2", "v2"}:
        try:
            from rag_version_2 import BGEM3RAG
        except Exception:
            logger.exception("RAG v2 requested but dependencies are missing; falling back to legacy")
        else:
            rag = BGEM3RAG(documents=kb_text)
            logger.info("RAG ready: strategy='{}', chunks={}", rag.strategy, rag.num_chunks)
            return rag, "", kb_text

    embedding_api_key = os.getenv("AZURE_OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY") or ""
    chunk_threshold = int(os.getenv("FAST_RAG_CHUNK_THRESHOLD", "20"))

    if not embedding_api_key:
        logger.warning(
            "No AZURE_OPENAI_API_KEY/OPENAI_API_KEY found. Forcing FastRAG mode (semantic embeddings disabled)."
        )
        chunk_threshold = 10**9

    rag = TieredRAG(
        documents=kb_text,
        api_key=embedding_api_key,
        chunk_threshold=chunk_threshold,
    )
    logger.info("RAG ready: strategy='{}', chunks={}", rag.strategy, rag.num_chunks)
    return rag, embedding_api_key, kb_text


def load_system_instruction() -> str:
    """Load Gemini Live system instruction from env or file with safe fallbacks."""
    env_prompt = os.getenv("GEMINI_SYSTEM_INSTRUCTION", "").strip()
    if env_prompt:
        logger.info("Using system instruction from GEMINI_SYSTEM_INSTRUCTION")
        return _with_tool_guidance(_strip_inline_kb(env_prompt))

    prompt_file = os.getenv("GEMINI_SYSTEM_PROMPT_FILE", "apsagent_system_prompt.txt")
    prompt_path = Path(prompt_file)
    if not prompt_path.is_absolute():
        prompt_path = Path(__file__).resolve().parent / prompt_path

    try:
        file_prompt = prompt_path.read_text(encoding="utf-8").strip()
        if file_prompt:
            logger.info("Loaded system instruction from '{}'", prompt_path)
            return _with_tool_guidance(_strip_inline_kb(file_prompt))
        logger.warning("System prompt file '{}' is empty. Using built-in fallback prompt.", prompt_path)
    except FileNotFoundError:
        logger.warning("System prompt file '{}' not found. Using built-in fallback prompt.", prompt_path)

    fallback = (
        "You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, "
        "so avoid emojis, bullet points, or other formatting that can't be spoken. "
        "Respond to what the user said in a creative, helpful, and brief way."
    )
    return _with_tool_guidance(fallback)


def create_gemini_live_service(tools: list[dict[str, Any]] | None = None) -> GeminiLiveLLMService:
    """Build a Gemini Live service instance with runtime configuration and logging."""
    google_api_key = os.getenv("GOOGLE_API_KEY")
    requested_model = os.getenv("GEMINI_MODEL", "models/gemini-3.1-flash-live-preview")
    voice = os.getenv("GEMINI_VOICE", "Charon")
    api_version = os.getenv("GEMINI_API_VERSION", "v1alpha")
    ws_open_timeout = float(os.getenv("GEMINI_WS_OPEN_TIMEOUT_SECS", "30"))
    system_instruction = load_system_instruction()

    # GeminiLiveLLMService requires a Live-capable model for realtime audio streaming.
    if requested_model in {"models/gemini-3.1-flash", "gemini-3.1-flash"}:
        effective_model = "models/gemini-3.1-flash-live-preview"
        logger.warning(
            "GEMINI_MODEL='{}' is not a Live model. Using '{}' for Gemini Live compatibility.",
            requested_model,
            effective_model,
        )
    else:
        effective_model = requested_model

    logger.info(
        "Initializing GeminiLiveLLMService with model='{}', api_version='{}', voice='{}', ws_open_timeout={}s",
        effective_model,
        api_version,
        voice,
        ws_open_timeout,
    )

    if not google_api_key:
        logger.warning("GOOGLE_API_KEY is not set. Gemini Live requests will fail at runtime.")

    try:
        return GeminiLiveLLMService(
            api_key=google_api_key,
            tools=tools,
            settings=GeminiLiveLLMService.Settings(
                model=effective_model,
                voice=voice,
                modalities=GeminiModalities.AUDIO,
                system_instruction=system_instruction,
            ),
            http_options=HttpOptions(
                api_version=api_version,
                async_client_args={"open_timeout": ws_open_timeout},
            ),
        )
    except Exception:
        logger.exception("Failed to initialize GeminiLiveLLMService")
        raise




async def run_bot(
    transport: BaseTransport,
    *,
    is_telephony: bool = False,
    smartflo_call_id: str = "",
    smartflo_call_direction: str = "",
):
    """Main bot logic.

    Args:
        transport: The Pipecat transport to use.
        is_telephony: True for SmartFlo/telephony calls. Switches Conv-TasNet
            to telephony mode (denoising with energy-based selection, lower
            VAD threshold, gain restoration) instead of browser mode (2-speaker
            separation with profile tracking).
    """
    logger.info("Starting bot (telephony={})" , is_telephony)

    rag, rag_api_key, kb_text = create_knowledge_rag()

    llm = create_gemini_live_service(
        tools=[
            {
                "function_declarations": [RAG_TOOL_DECLARATION],
            }
        ]
    )

    # --- Conv-TasNet Speech Separation ---
    # Two operating modes:
    #   Browser:   2-speaker separation (YouTube/TV cross-talk) + profile tracking
    #   Telephony: 1-speaker denoising (field noise) + energy selection + gain restore
    def _optional_float_env(name: str, default: float | None = None) -> float | None:
        value = os.getenv(name, "").strip()
        return float(value) if value else default

    def _optional_int_env(name: str, default: int | None = None) -> int | None:
        value = os.getenv(name, "").strip()
        return int(value) if value else default

    convtasnet_enabled = os.getenv("CONVTASNET_ENABLED", "true").lower() in ("1", "true", "yes")
    convtasnet_chunk = float(os.getenv("CONVTASNET_CHUNK_SEC", "0.4"))
    default_vad = "0.01" if is_telephony else "0.001"
    convtasnet_vad = float(os.getenv("CONVTASNET_VAD_THRESHOLD", default_vad))
    convtasnet_telephony_strategy = os.getenv("CONVTASNET_TELEPHONY_STRATEGY", "profile")
    default_profile_lock_min_energy = 0.0015 if is_telephony else None
    default_profile_min_similarity = 0.6 if is_telephony else None
    default_energy_ratio_db_min = 6.0 if is_telephony else None
    default_speech_hold_chunks = 2 if is_telephony else 0
    convtasnet_profile_lock_min_energy = _optional_float_env(
        "CONVTASNET_PROFILE_LOCK_MIN_ENERGY",
        default_profile_lock_min_energy,
    )
    convtasnet_profile_min_similarity = _optional_float_env(
        "CONVTASNET_PROFILE_MIN_SIMILARITY",
        default_profile_min_similarity,
    )
    convtasnet_energy_ratio_db_min = _optional_float_env(
        "CONVTASNET_ENERGY_RATIO_DB_MIN",
        default_energy_ratio_db_min,
    )
    convtasnet_speech_hold_chunks = _optional_int_env(
        "CONVTASNET_SPEECH_HOLD_CHUNKS",
        default_speech_hold_chunks,
    )

    speech_separator = None
    if convtasnet_enabled:
        speech_separator = ConvTasNetProcessor(
            chunk_duration=convtasnet_chunk,
            vad_threshold=convtasnet_vad,
            telephony_mode=is_telephony,
            telephony_strategy=convtasnet_telephony_strategy,
            profile_lock_min_energy=convtasnet_profile_lock_min_energy,
            profile_min_similarity=convtasnet_profile_min_similarity,
            energy_ratio_db_min=convtasnet_energy_ratio_db_min,
            speech_hold_chunks=convtasnet_speech_hold_chunks or 0,
        )
    else:
        logger.info("Conv-TasNet speech separation DISABLED")

    rag_max_context_chars = int(os.getenv("RAG_MAX_CONTEXT_CHARS", "5000"))
    rag_max_context_chars_detail = int(os.getenv("RAG_MAX_CONTEXT_CHARS_DETAIL", "7500"))
    rag_max_chunks = int(os.getenv("RAG_MAX_CHUNKS", "4"))
    rag_max_chunks_detail = int(os.getenv("RAG_MAX_CHUNKS_DETAIL", "6"))

    async def handle_retrieve_knowledge(params: FunctionCallParams):
        query = str(params.arguments.get("query", "")).strip()
        if not query:
            await params.result_callback(
                {
                    "context": (
                        "క్షమించండి, మీ ప్రశ్న స్పష్టంగా అర్థం కాలేదు. "
                        "దయచేసి పంట పేరు మరియు సమస్యను ఒక చిన్న వాక్యంలో చెప్పండి."
                    )
                }
            )
            return

        logger.info("RAG tool call [{}] query='{}'", params.tool_call_id, query)

        try:
            retrieved = await rag.retrieve_async(query, api_key=rag_api_key)
        except Exception:
            logger.exception("RAG retrieval failed")
            await params.result_callback(
                {
                    "context": (
                        "క్షమించండి, ప్రస్తుతం నాలెడ్జ్ బేస్ నుంచి సమాచారం తెచ్చేటప్పుడు సమస్య వచ్చింది. "
                        "దయచేసి అదే ప్రశ్నను మరోసారి చెప్పగలరా?"
                    )
                }
            )
            return

        if not retrieved:
            retrieved = "No relevant information found in the knowledge base."

        retrieved = prepare_rag_context(query, retrieved, kb_text)

        detail_intent = _is_detail_intent(query)
        target_max_chunks = rag_max_chunks_detail if detail_intent else rag_max_chunks
        target_max_chars = rag_max_context_chars_detail if detail_intent else rag_max_context_chars

        # Keep payload compact by default; allow larger context only for explicit detailed requests.
        retrieved = _limit_rag_chunks(retrieved, target_max_chunks)

        chunk_count_before_trim = _count_rag_chunks(retrieved)
        trimmed = False
        if len(retrieved) > target_max_chars:
            # Keep tool payload bounded to control response latency and token usage.
            retrieved = retrieved[:target_max_chars]
            trimmed = True

        chunk_count_after_trim = _count_rag_chunks(retrieved)
        preview = retrieved[:220].replace("\n", " ")
        logger.info(
            "RAG result [{}]: detail_intent={}, max_chunks={}, max_chars={}, chunks_before={}, chunks_after={}, chars={}, trimmed={}, preview='{}'",
            params.tool_call_id,
            detail_intent,
            target_max_chunks,
            target_max_chars,
            chunk_count_before_trim,
            chunk_count_after_trim,
            len(retrieved),
            trimmed,
            preview,
        )

        await params.result_callback({"context": retrieved})

    llm.register_function(
        "retrieve_knowledge",
        handle_retrieve_knowledge,
        cancel_on_interruption=False,
        timeout_secs=25,
    )



    context = LLMContext()
    # Gemini Live uses server-side VAD by default, so local VAD is not required.
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(context)


    


    # Pipeline - assembled from reusable components
    # When Conv-TasNet is enabled, it sits between input and aggregator
    # to clean overlapping speaker audio before Gemini Live sees it.
    pipeline_components = [transport.input()]
    if speech_separator:
        pipeline_components.append(speech_separator)
    pipeline_components += [
        user_aggregator,
        llm,
    ]

    if is_telephony:
        pipeline_components.append(
            EscalationDetector(
                task=None,
                call_id=smartflo_call_id,
                call_direction=smartflo_call_direction,
            )
        )

    pipeline_components += [
        transport.output(),
        assistant_aggregator,
    ]
    pipeline = Pipeline(pipeline_components)


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[
        ],
    )

    if is_telephony:
        for processor in pipeline_components:
            if isinstance(processor, EscalationDetector) and processor._task is None:
                processor._task = task

    conversation_started = False

    async def start_conversation_once():
        nonlocal conversation_started
        if conversation_started:
            return
        conversation_started = True
        logger.info("Queuing initial assistant introduction")
        context.add_message({"role": "user", "content": "Please introduce yourself."})
        await task.queue_frames([LLMRunFrame()])

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        await start_conversation_once()

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        await start_conversation_once()

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case DailyRunnerArguments():
            try:
                from pipecat.transports.daily.transport import DailyTransport, DailyParams
            except ImportError:
                logger.error(
                    "Daily transport dependencies are not installed. "
                    "Install pipecat-ai with the 'daily' extra to use --transport daily."
                )
                return

            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport, is_telephony=False)


# ---------------------------------------------------------------------------
#  SmartFlo Telephony Support
# ---------------------------------------------------------------------------

async def _parse_smartflo_start(websocket) -> dict:
    """Read SmartFlo lifecycle events and extract stream metadata."""
    # Check query params first (some SmartFlo deployments pass IDs here)
    query_stream_id = str(
        websocket.query_params.get("streamSid")
        or websocket.query_params.get("stream_id")
        or ""
    ).strip()
    query_call_id = str(
        websocket.query_params.get("callSid")
        or websocket.query_params.get("call_id")
        or ""
    ).strip()
    query_direction = _normalize_call_direction(
        websocket.query_params.get("direction")
        or websocket.query_params.get("callDirection")
        or ""
    )
    if query_stream_id:
        logger.info("SmartFlo metadata from query params: stream_id={}", bool(query_stream_id))
        return {
            "stream_id": query_stream_id,
            "call_id": query_call_id,
            "direction": query_direction,
        }

    for _ in range(25):
        try:
            message = await asyncio.wait_for(websocket.receive(), timeout=2.0)
        except asyncio.TimeoutError:
            continue
        except Exception:
            logger.exception("Failed waiting for SmartFlo start metadata")
            break

        msg_type = str(message.get("type", "")).strip().lower()
        if msg_type == "websocket.disconnect":
            logger.warning("SmartFlo disconnected before start metadata")
            return {"stream_id": "", "call_id": "", "direction": ""}
        if msg_type != "websocket.receive":
            continue

        raw_text = message.get("text")
        if raw_text is None and message.get("bytes") is not None:
            raw_text = message["bytes"].decode("utf-8", errors="ignore")
        if not raw_text:
            continue

        try:
            data = json.loads(raw_text)
        except json.JSONDecodeError:
            continue

        event = str(data.get("event", "")).strip().lower()
        start = data.get("start") or {}
        if not isinstance(start, dict):
            start = {}

        stream_id = str(
            start.get("streamSid") or data.get("streamSid")
            or start.get("stream_id") or data.get("stream_id") or ""
        ).strip()
        call_id = str(
            start.get("callSid") or data.get("callSid")
            or start.get("call_id") or data.get("call_id") or ""
        ).strip()
        direction = _normalize_call_direction(start.get("direction") or data.get("direction") or "")

        logger.info(
            "SmartFlo event='{}' stream_id={} call_id={} direction={}",
            event,
            bool(stream_id),
            bool(call_id),
            direction or "unknown",
        )

        if stream_id and event in {"connected", "start", "media", "mark", "dtmf", "stop"}:
            return {"stream_id": stream_id, "call_id": call_id, "direction": direction}
        if event == "start":
            return {"stream_id": stream_id, "call_id": call_id, "direction": direction}

    logger.error("SmartFlo start metadata not found")
    return {"stream_id": "", "call_id": "", "direction": ""}


async def smartflo_bot(websocket):
    """Handle a SmartFlo telephony call using the same run_bot() pipeline."""
    call_data = await _parse_smartflo_start(websocket)
    if not call_data["stream_id"]:
        logger.error("Missing SmartFlo stream_id; aborting call")
        try:
            await websocket.close(code=1011)
        except Exception:
            pass
        return

    logger.info(
        "SmartFlo call started: stream_id={} call_id={} direction={}",
        call_data["stream_id"],
        call_data["call_id"],
        call_data.get("direction") or "unknown",
    )

    serializer = SmartFloFrameSerializer(
        stream_sid=call_data["stream_id"],
        call_sid=call_data["call_id"],
    )

    transport = FastAPIWebsocketTransport(
        websocket=websocket,
        params=FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
            add_wav_header=False,
            serializer=serializer,
        ),
    )

    await run_bot(
        transport,
        is_telephony=True,
        smartflo_call_id=call_data["call_id"],
        smartflo_call_direction=call_data.get("direction", ""),
    )


if __name__ == "__main__":
    from fastapi import WebSocket, WebSocketDisconnect
    from pipecat.runner.run import main, _create_server_app
    import argparse
    import sys

    # Hook into the runner to add /ws/smartflo AFTER the standard app is created
    _original_create_app = _create_server_app

    def _patched_create_app(args: argparse.Namespace):
        app = _original_create_app(args)

        # Add SmartFlo telephony endpoint to the existing WebRTC server
        @app.websocket("/ws/smartflo")
        async def smartflo_endpoint(websocket: WebSocket):
            await websocket.accept()
            logger.info("SmartFlo connection from {}", websocket.client)
            try:
                await smartflo_bot(websocket)
            except WebSocketDisconnect:
                logger.info("SmartFlo call ended (WebSocket disconnected)")
            except Exception as e:
                logger.error("SmartFlo session error: {}", e)

        @app.get("/health")
        async def health():
            return {"status": "ok", "agent": "apsagent", "ws_smartflo": "/ws/smartflo"}

        logger.info("SmartFlo endpoint registered: /ws/smartflo")
        return app

    # Monkey-patch so pipecat.runner.run.main() uses our patched factory
    import pipecat.runner.run as _run_module
    _run_module._create_server_app = _patched_create_app

    main()